#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# exec = caelestia shell -d
exec-once = wl-paste --watch cliphist store &
exec-once = mako
exec-once = awww-daemon 
exec-once = awww img ~/dotfiles/assets/wallpaper.png --transition-type bottom

# exec-once = waybar &
# exec-once = swww-daemon &
# exec-once = dunst
